// Vendors the web fonts locally so the app never fetches them from Google at runtime — a
// privacy-first native app must not phone home (IP + launch times) or depend on the network
// to render. Newsreader and Noto are both SIL Open Font License, which permits bundling.
//
// Run once (and again to refresh): `node scripts/vendor-fonts.mjs`. It writes woff2 files to
// app/fonts/ and a self-contained app/styles/fonts.css with local `url(...)` references.
//
// Idempotent: re-running overwrites the same files. Fonts are only re-downloaded here, never at
// runtime, so this script — not the app — is the one place that talks to Google.

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = join(HERE, '..', 'app');
const FONTS_DIR = join(APP, 'fonts');
const OUT_CSS = join(APP, 'styles', 'fonts.css');

// A modern browser UA so Google serves woff2 (the default UA gets older formats).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36';

// The families the app uses. `script` matches i18n.js's FONTS keys; the wordmark + serif
// headings use Newsreader (latin), names in RTL/Ethiopic locales use the Noto families.
const FAMILIES = [
  { script: 'latin', url: 'https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&display=swap' },
  { script: 'arabic', url: 'https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap' },
  { script: 'ethiopic', url: 'https://fonts.googleapis.com/css2?family=Noto+Sans+Ethiopic:wght@400;500;600;700&display=swap' },
];

async function get(url, asBuffer = false) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

async function main() {
  await mkdir(FONTS_DIR, { recursive: true });
  const seen = new Set();
  const sections = [];
  for (const { script, url } of FAMILIES) {
    let css = await get(url);
    const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
    for (const remote of urls) {
      const base = script + '-' + remote.split('/').pop();
      if (!seen.has(base)) {
        seen.add(base);
        await writeFile(join(FONTS_DIR, base), await get(remote, true));
      }
      css = css.replaceAll(remote, `../fonts/${base}`);
    }
    sections.push(`/* ${script} — vendored from Google Fonts (SIL OFL) */\n${css.trim()}`);
    console.log(`${script}: ${urls.length} file(s)`);
  }
  const header = '/* Generated by scripts/vendor-fonts.mjs — do not edit by hand. Fonts under the SIL\n   Open Font License; run the script to refresh. */\n\n';
  await writeFile(OUT_CSS, header + sections.join('\n\n') + '\n');
  console.log(`→ ${OUT_CSS} (${seen.size} woff2 total)`);
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
