// @generated by scripts/gen-error-codes.mjs from error-codes.json — DO NOT EDIT.
#![allow(dead_code)]

//! The closed error-code registry (server mirror). See `plan/design.error-model.md`.

/// One row of code metadata.
pub struct CodeMeta {
    pub code: &'static str,
    pub domain: &'static str,
    pub retriable: bool,
    pub action: Option<&'static str>,
}

pub const BELOW_GC_FLOOR: &str = "below_gc_floor";
pub const QUOTA_EXCEEDED: &str = "quota_exceeded";
pub const RATE_LIMITED: &str = "rate_limited";
pub const VERSION_CONFLICT: &str = "version_conflict";
pub const COVERED_ANOMALY: &str = "covered_anomaly";
pub const INVALID_REQUEST: &str = "invalid_request";
pub const ACCESS_DENIED: &str = "access_denied";
pub const NOT_FOUND: &str = "not_found";
pub const UNAVAILABLE: &str = "unavailable";
pub const REQUEST_FAILED: &str = "request_failed";
pub const OFFLINE: &str = "offline";
pub const TIMEOUT: &str = "timeout";
pub const AUTH_REQUIRED: &str = "auth_required";
pub const SESSION_EXPIRED: &str = "session_expired";
pub const SIGN_IN_FAILED: &str = "sign_in_failed";
pub const SIGN_UP_FAILED: &str = "sign_up_failed";
pub const EMAIL_TAKEN: &str = "email_taken";
pub const WRONG_PASSPHRASE: &str = "wrong_passphrase";
pub const TAMPERED_ANCHOR: &str = "tampered_anchor";
pub const RECOVERY_CODE_INVALID: &str = "recovery_code_invalid";
pub const KEYRING_VERIFY_FAILED: &str = "keyring_verify_failed";
pub const DECRYPT_FAILED: &str = "decrypt_failed";
pub const STORAGE_QUOTA: &str = "storage_quota";
pub const STORAGE_BLOCKED: &str = "storage_blocked";
pub const STORAGE_CORRUPT: &str = "storage_corrupt";
pub const WORKER_UNAVAILABLE: &str = "worker_unavailable";
pub const INTERNAL: &str = "internal";

/// Every code + its metadata, in source order.
pub const ERROR_CODES: &[CodeMeta] = &[
    CodeMeta { code: "below_gc_floor", domain: "sync", retriable: false, action: Some("bootstrap") },
    CodeMeta { code: "quota_exceeded", domain: "sync", retriable: false, action: Some("upgrade") },
    CodeMeta { code: "rate_limited", domain: "sync", retriable: true, action: Some("retry") },
    CodeMeta { code: "version_conflict", domain: "sync", retriable: true, action: Some("retry") },
    CodeMeta { code: "covered_anomaly", domain: "sync", retriable: false, action: Some("contact") },
    CodeMeta { code: "invalid_request", domain: "sync", retriable: false, action: Some("contact") },
    CodeMeta { code: "access_denied", domain: "sync", retriable: false, action: None },
    CodeMeta { code: "not_found", domain: "sync", retriable: false, action: None },
    CodeMeta { code: "unavailable", domain: "sync", retriable: true, action: Some("retry") },
    CodeMeta { code: "request_failed", domain: "sync", retriable: true, action: Some("retry") },
    CodeMeta { code: "offline", domain: "sync", retriable: true, action: Some("retry") },
    CodeMeta { code: "timeout", domain: "sync", retriable: true, action: Some("retry") },
    CodeMeta { code: "auth_required", domain: "auth", retriable: false, action: Some("reauth") },
    CodeMeta { code: "session_expired", domain: "auth", retriable: false, action: Some("reauth") },
    CodeMeta { code: "sign_in_failed", domain: "auth", retriable: false, action: None },
    CodeMeta { code: "sign_up_failed", domain: "auth", retriable: false, action: None },
    CodeMeta { code: "email_taken", domain: "auth", retriable: false, action: None },
    CodeMeta { code: "wrong_passphrase", domain: "vault", retriable: false, action: None },
    CodeMeta { code: "tampered_anchor", domain: "vault", retriable: false, action: Some("contact") },
    CodeMeta { code: "recovery_code_invalid", domain: "vault", retriable: false, action: None },
    CodeMeta { code: "keyring_verify_failed", domain: "vault", retriable: false, action: Some("contact") },
    CodeMeta { code: "decrypt_failed", domain: "vault", retriable: false, action: Some("contact") },
    CodeMeta { code: "storage_quota", domain: "storage", retriable: false, action: Some("contact") },
    CodeMeta { code: "storage_blocked", domain: "storage", retriable: false, action: Some("contact") },
    CodeMeta { code: "storage_corrupt", domain: "storage", retriable: false, action: Some("contact") },
    CodeMeta { code: "worker_unavailable", domain: "app", retriable: false, action: Some("upgrade") },
    CodeMeta { code: "internal", domain: "app", retriable: false, action: Some("contact") },
];

/// Interpolation args for `quota_exceeded`.
pub struct QuotaExceededArgs {
    pub limit: u64,
    pub used: u64,
}

